# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hand_interface/flex_sns.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class flex_sns(genpy.Message):
  _md5sum = "57e523c8816fb6474dc2708662828753"
  _type = "hand_interface/flex_sns"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 curl1
int32 hype1
int32 curl2
int32 hype2
int32 curl3
int32 hype3
int32 curl4
int32 hype4
"""
  __slots__ = ['curl1','hype1','curl2','hype2','curl3','hype3','curl4','hype4']
  _slot_types = ['int32','int32','int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       curl1,hype1,curl2,hype2,curl3,hype3,curl4,hype4

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(flex_sns, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.curl1 is None:
        self.curl1 = 0
      if self.hype1 is None:
        self.hype1 = 0
      if self.curl2 is None:
        self.curl2 = 0
      if self.hype2 is None:
        self.hype2 = 0
      if self.curl3 is None:
        self.curl3 = 0
      if self.hype3 is None:
        self.hype3 = 0
      if self.curl4 is None:
        self.curl4 = 0
      if self.hype4 is None:
        self.hype4 = 0
    else:
      self.curl1 = 0
      self.hype1 = 0
      self.curl2 = 0
      self.hype2 = 0
      self.curl3 = 0
      self.hype3 = 0
      self.curl4 = 0
      self.hype4 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8i().pack(_x.curl1, _x.hype1, _x.curl2, _x.hype2, _x.curl3, _x.hype3, _x.curl4, _x.hype4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.curl1, _x.hype1, _x.curl2, _x.hype2, _x.curl3, _x.hype3, _x.curl4, _x.hype4,) = _get_struct_8i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8i().pack(_x.curl1, _x.hype1, _x.curl2, _x.hype2, _x.curl3, _x.hype3, _x.curl4, _x.hype4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.curl1, _x.hype1, _x.curl2, _x.hype2, _x.curl3, _x.hype3, _x.curl4, _x.hype4,) = _get_struct_8i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8i = None
def _get_struct_8i():
    global _struct_8i
    if _struct_8i is None:
        _struct_8i = struct.Struct("<8i")
    return _struct_8i
